// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: control_plane_v2.proto

package v2

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A description of a Data Plane api region
type DataPlaneRegion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url            string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Lat            float64  `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon            float64  `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Region         string   `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Labels         []string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	DefaultPrimary bool     `protobuf:"varint,7,opt,name=default_primary,json=defaultPrimary,proto3" json:"default_primary,omitempty"`
	DefaultBackup  bool     `protobuf:"varint,8,opt,name=default_backup,json=defaultBackup,proto3" json:"default_backup,omitempty"`
	Status         string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DataPlaneRegion) Reset() {
	*x = DataPlaneRegion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_v2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPlaneRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPlaneRegion) ProtoMessage() {}

func (x *DataPlaneRegion) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_v2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPlaneRegion.ProtoReflect.Descriptor instead.
func (*DataPlaneRegion) Descriptor() ([]byte, []int) {
	return file_control_plane_v2_proto_rawDescGZIP(), []int{0}
}

func (x *DataPlaneRegion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataPlaneRegion) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DataPlaneRegion) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *DataPlaneRegion) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *DataPlaneRegion) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *DataPlaneRegion) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DataPlaneRegion) GetDefaultPrimary() bool {
	if x != nil {
		return x.DefaultPrimary
	}
	return false
}

func (x *DataPlaneRegion) GetDefaultBackup() bool {
	if x != nil {
		return x.DefaultBackup
	}
	return false
}

func (x *DataPlaneRegion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// The primary and backup urls for the closest
// data plane regions to a user
//
// Response for GET "/regions/locate"
type DataRegionsLocateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimaryUrl        string `protobuf:"bytes,1,opt,name=primary_url,json=primaryUrl,proto3" json:"primary_url,omitempty"`
	BackupUrl         string `protobuf:"bytes,2,opt,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	PrimaryNetworkUrl string `protobuf:"bytes,3,opt,name=primary_network_url,json=primaryNetworkUrl,proto3" json:"primary_network_url,omitempty"`
	BackupNetworkUrl  string `protobuf:"bytes,4,opt,name=backup_network_url,json=backupNetworkUrl,proto3" json:"backup_network_url,omitempty"`
}

func (x *DataRegionsLocateResponse) Reset() {
	*x = DataRegionsLocateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_v2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRegionsLocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRegionsLocateResponse) ProtoMessage() {}

func (x *DataRegionsLocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_v2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRegionsLocateResponse.ProtoReflect.Descriptor instead.
func (*DataRegionsLocateResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_v2_proto_rawDescGZIP(), []int{1}
}

func (x *DataRegionsLocateResponse) GetPrimaryUrl() string {
	if x != nil {
		return x.PrimaryUrl
	}
	return ""
}

func (x *DataRegionsLocateResponse) GetBackupUrl() string {
	if x != nil {
		return x.BackupUrl
	}
	return ""
}

func (x *DataRegionsLocateResponse) GetPrimaryNetworkUrl() string {
	if x != nil {
		return x.PrimaryNetworkUrl
	}
	return ""
}

func (x *DataRegionsLocateResponse) GetBackupNetworkUrl() string {
	if x != nil {
		return x.BackupNetworkUrl
	}
	return ""
}

// The list of data plane regions
//
// Response to GET "/regions"
type DataRegionsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regions []*DataPlaneRegion `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
}

func (x *DataRegionsListResponse) Reset() {
	*x = DataRegionsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_v2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRegionsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRegionsListResponse) ProtoMessage() {}

func (x *DataRegionsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_v2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRegionsListResponse.ProtoReflect.Descriptor instead.
func (*DataRegionsListResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_v2_proto_rawDescGZIP(), []int{2}
}

func (x *DataRegionsListResponse) GetRegions() []*DataPlaneRegion {
	if x != nil {
		return x.Regions
	}
	return nil
}

// The request body for upgrading a Public
// Token to a Permissive Token or a User Authenticated
// (Strict) Token. The UserId can only be set by
// making the request with a SecretToken in the
// Authorization Header. If using the PublicToken,
// DO NOT pass the UserId.
//
// Performing this request for a Strict Token means
// that a UserId will be tracked against Bundles
// sent using the returned token
//
// Request for POST "/tokens/upgrade"
type TokenUpgradeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicToken string `protobuf:"bytes,1,opt,name=public_token,json=publicToken,proto3" json:"public_token,omitempty"`
	// The authenticated user_id to attach to captured data.
	// This should be validated by the customer backend.
	// DO NOT pass if using a public token for Authorization
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The duration the token is valid expressed in seconds.
	// May be capped to a maximum by backend token upgrade
	// handlers.
	ExpiresInSeconds   int32 `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	MaxIdleTimeMinutes int32 `protobuf:"varint,4,opt,name=max_idle_time_minutes,json=maxIdleTimeMinutes,proto3" json:"max_idle_time_minutes,omitempty"`
}

func (x *TokenUpgradeRequest) Reset() {
	*x = TokenUpgradeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_v2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUpgradeRequest) ProtoMessage() {}

func (x *TokenUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_v2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUpgradeRequest.ProtoReflect.Descriptor instead.
func (*TokenUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_v2_proto_rawDescGZIP(), []int{3}
}

func (x *TokenUpgradeRequest) GetPublicToken() string {
	if x != nil {
		return x.PublicToken
	}
	return ""
}

func (x *TokenUpgradeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenUpgradeRequest) GetExpiresInSeconds() int32 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

func (x *TokenUpgradeRequest) GetMaxIdleTimeMinutes() int32 {
	if x != nil {
		return x.MaxIdleTimeMinutes
	}
	return 0
}

// An app access token with a a customer
// authenticated UserId attached.
//
// Response for POST "/tokens/upgrade"
type TokenUpgradeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppAccessToken string `protobuf:"bytes,1,opt,name=app_access_token,json=appAccessToken,proto3" json:"app_access_token,omitempty"`
}

func (x *TokenUpgradeResponse) Reset() {
	*x = TokenUpgradeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_v2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUpgradeResponse) ProtoMessage() {}

func (x *TokenUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_v2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUpgradeResponse.ProtoReflect.Descriptor instead.
func (*TokenUpgradeResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_v2_proto_rawDescGZIP(), []int{4}
}

func (x *TokenUpgradeResponse) GetAppAccessToken() string {
	if x != nil {
		return x.AppAccessToken
	}
	return ""
}

// Revoke Token request to invalidate previously
// created tokens for a specific use. Invalidates
// Strict mode tokens.
//
// Request for POST "/tokens/revoke"
type RevokeAppTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RevokeAppTokenRequest) Reset() {
	*x = RevokeAppTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_control_plane_v2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeAppTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAppTokenRequest) ProtoMessage() {}

func (x *RevokeAppTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_v2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAppTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeAppTokenRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_v2_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeAppTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_control_plane_v2_proto protoreflect.FileDescriptor

var file_control_plane_v2_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x5f,
	0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x76, 0x32, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x6d,
	0x61, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x19, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x2c, 0x0a, 0x12, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x55, 0x72, 0x6c, 0x22, 0x55, 0x0a, 0x17, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x76, 0x32, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61,
	0x6e, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xbb, 0x01, 0x0a, 0x13,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x20, 0x01, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x15, 0x6d, 0x61, 0x78, 0x5f, 0x69, 0x64,
	0x6c, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x6d, 0x61, 0x78, 0x49, 0x64, 0x6c, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x14, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x70, 0x70,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x39, 0x0a, 0x15, 0x52,
	0x65, 0x76, 0x6f, 0x6b, 0x65, 0x41, 0x70, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x20, 0x01, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x64, 0x0a, 0x23, 0x69, 0x6f, 0x2e, 0x6d, 0x6f, 0x6f,
	0x6e, 0x73, 0x65, 0x6e, 0x73, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x32,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x42, 0x14, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x56, 0x32, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x5a, 0x27, 0x6d, 0x6f, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x65, 0x2e, 0x69,
	0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x2d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x3b, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_control_plane_v2_proto_rawDescOnce sync.Once
	file_control_plane_v2_proto_rawDescData = file_control_plane_v2_proto_rawDesc
)

func file_control_plane_v2_proto_rawDescGZIP() []byte {
	file_control_plane_v2_proto_rawDescOnce.Do(func() {
		file_control_plane_v2_proto_rawDescData = protoimpl.X.CompressGZIP(file_control_plane_v2_proto_rawDescData)
	})
	return file_control_plane_v2_proto_rawDescData
}

var file_control_plane_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_control_plane_v2_proto_goTypes = []interface{}{
	(*DataPlaneRegion)(nil),           // 0: v2.controlplane.DataPlaneRegion
	(*DataRegionsLocateResponse)(nil), // 1: v2.controlplane.DataRegionsLocateResponse
	(*DataRegionsListResponse)(nil),   // 2: v2.controlplane.DataRegionsListResponse
	(*TokenUpgradeRequest)(nil),       // 3: v2.controlplane.TokenUpgradeRequest
	(*TokenUpgradeResponse)(nil),      // 4: v2.controlplane.TokenUpgradeResponse
	(*RevokeAppTokenRequest)(nil),     // 5: v2.controlplane.RevokeAppTokenRequest
}
var file_control_plane_v2_proto_depIdxs = []int32{
	0, // 0: v2.controlplane.DataRegionsListResponse.regions:type_name -> v2.controlplane.DataPlaneRegion
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_control_plane_v2_proto_init() }
func file_control_plane_v2_proto_init() {
	if File_control_plane_v2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_control_plane_v2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPlaneRegion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_plane_v2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRegionsLocateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_plane_v2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRegionsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_plane_v2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenUpgradeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_plane_v2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenUpgradeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_control_plane_v2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokeAppTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_control_plane_v2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_plane_v2_proto_goTypes,
		DependencyIndexes: file_control_plane_v2_proto_depIdxs,
		MessageInfos:      file_control_plane_v2_proto_msgTypes,
	}.Build()
	File_control_plane_v2_proto = out.File
	file_control_plane_v2_proto_rawDesc = nil
	file_control_plane_v2_proto_goTypes = nil
	file_control_plane_v2_proto_depIdxs = nil
}
